### ISSUE TITLE
assets/testdataを作成する方法がわからない

### ISSUE THREAD

**Issue by matsuu** [isucon/isucon9-final#224]
手元の環境で再現しようとしていますが、一通り手順をなぞってみたもののassets/testdataが生成されずbenchを実行できません。どこかでダウンロードできたりするんでしょうか。

**Comment by tukeJonny** [comment]
@matsuu 
問題のご報告ありがとうございます！
返答が遅れてしまって申し訳ないです。

> どこかでダウンロードできたりするんでしょうか。

assets/testdataとして指定されているものは、ベンチマーカーで定義されたオプション `--assetdir` の[指定](https://github.com/isucon/isucon9-final/blob/master/bench/cmd/bench/bench.go#L87,L92)と対応し、これはフロントエンドの静的ファイル群を格納したディレクトリを指定する想定となっています。
そのため、別の場所からダウンロードする想定ではありません。

---

ベンチマーカーについて、[こちら](https://github.com/isucon/isucon9-final#%E3%83%99%E3%83%B3%E3%83%81%E3%83%9E%E3%83%BC%E3%82%AB%E3%83%BC%E3%81%AE%E8%B5%B7%E5%8B%95%E6%96%B9%E6%B3%95)の実行方法にあるように、オプションとして `--assetdir=<フロントエンドのビルド結果が配置されたディレクトリ>` を指定する必要があります。
(オプションを指定しない場合はデフォルト値として適当なディレクトリが指定されますので、正しく実行できないケースがあります)

frontendのビルドについては別途、[こちら](https://github.com/isucon/isucon9-final/tree/master/webapp/frontend#frontend) に案内がありますので、これに沿ってビルドいただく必要があります (frontendのビルド成果物を `--assetdir` に指定する必要があるため、事前にビルドが必要です)。

上記２点をまとめると、以下のように実行を進めればベンチ走行できるイメージです (課金APIは別途[README](https://github.com/isucon/isucon9-final/tree/master/blackbox/payment#paymentapi)をご参照の上セットアップください。また、localhostではない場所で課金APIやwebappを動作させている場合は指定を変更する必要があります）。

```
$ cd isucon9-final
$ (cd webapp/frontend && make)
$ (cd bench && make)
$ ./bench/bin/bench_linux run --payment=http://localhost:5000 --target=http://localhost:8080 --assetdir=webapp/frontend/dist
```

上記手順でも実行できない場合は、より詳細な調査が必要かもしれませんので、実施された手順や発生したエラー等を共有いただけると助かります。

**Comment by matsuu** [comment]
ありがとうございます。同梱のansibleを使うと想定通りのディレクトリ構成にならないのが原因だったようです。ご提示いただいた内容で再チャレンジしてみます。

**Comment by matsuu** [comment]
解決しました。ありがとうございました。
